# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Generate Core Data Model
      run: /Applications/Xcode.app/Contents/Developer/usr/bin/momc --sdkroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk --iphoneos-deployment-target 18.0 --module NoSimulatorModel NoSimulatorModel/Sources/NoSimulatorModel/Resources/NoSimulatorCoreDataModel.xcdatamodeld NoSimulatorModel/Sources/NoSimulatorModel/Resources
    - name: Run tests
      run: |
        cd NoSimulatorModel
        swift test -v
